kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginxingress-clusterrole
  namespace: nginxingress-namespace
subjects:
- kind: ServiceAccount
  name: nginxingress-serviceaccount
  namespace: nginxingress-namespace
roleRef:
  kind: ClusterRole
  name: nginxingress-clusterrole
  apiGroup: rbac.authorization.k8s.io
