kind: Service
apiVersion: v1
metadata:
  name: testappone-service
  namespace: testappone-namespace
spec:
  clusterIP: 10.245.213.91 # designated IP for matching examples
  selector:
    app: testappone
  ports:
  - protocol: TCP
    port: 80
