apiVersion: apps/v1
kind: Deployment
metadata:
  name: testappapi-deployment
  namespace: testappapi-namespace
  labels:
    app: testappapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testappapi
  template:
    metadata:
      labels:
        app: testappapi
    spec:
      containers:
      - name: testappapi
        image: nginx
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: testappapi-index
          mountPath: /usr/share/nginx/html
      volumes:
      - name: testappapi-index
        configMap:
          name: testappapi-configmap
          items:
          - key: index.html
            path: index.html
