apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapptwo-deployment
  namespace: testapptwo-namespace
  labels:
    app: testapptwo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapptwo
  template:
    metadata:
      namespace: testapptwo-namespace
      labels:
        app: testapptwo
    spec:
      containers:
      - name: testapptwo
        image: nginx
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: testapptwo-index
          mountPath: /usr/share/nginx/html
      volumes:
      - name: testapptwo-index
        configMap:
          name: testapptwo-configmap
          items:
          - key: index.html
            path: index.html
