apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxingress-daemonset
  namespace: nginxingress-namespace
spec:
  selector:
    matchLabels:
      app: nginxingress-daemonset-pod
  template:
    metadata:
      namespace: nginxingress-namespace
      labels:
        app: nginxingress-daemonset-pod
    spec:
      serviceAccountName: nginxingress-serviceaccount
      terminationGracePeriodSeconds: 15
      containers:
      - image: nginx/nginx-ingress:alpine
        name: nginxingress-daemonset-pod
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-configmaps=$(POD_NAMESPACE)/nginxingress-configmap
          - -default-server-tls-secret=$(POD_NAMESPACE)/nginxingress-test-tls-secret
         #- -v=3 # Enables extensive logging. Useful for trooublshooting.
         #- -report-ingress-status
         #- -external-service=nginx-ingress
         #- -enable-leader-election
